### ISSUE TITLE
[detalle] mejorar test de cambio de password

### ISSUE THREAD

**Issue by ngarbezza** [tomasnozica/TerminalJavascript#10]
En lugar de acceder a la property `password`, estaría bueno hacer un test más "funcional" y probar a loguearse en la consola con el password viejo (no debería poder entrar) y con el password nuevo (debería entrar).

https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/index.js#L132

**Comment by tomasnozica** [comment]
Intente cambiarlo pero hay algun problema

```
test('18 - Cambio la clave y puedo entrar con la nueva', (c) => {
    c.consola.login(c.rootUser);
    c.consola.newUser(c.usuario);
    c.consola.logout();
    c.consola.login(c.usuario);
    c.consola.changeUserPassword('clave','12456');
    c.consola.logout();
    c.consola.login(c.userNewPass);
    return assertTrue(c.consola.usuarioLogueado == c.userNewPass)
  });
```

**Comment by tomasnozica** [comment]
Creo que es que el validateUser compara si es exactamente el mismo objeto y no con el mismo contenido, me parece.

**Comment by tomasnozica** [comment]
Quedo corregido!
```
test('18 - Cambio la clave y puedo entrar con la nueva', (c) => {
    c.consola.login(c.rootUser);
    c.consola.newUser(c.usuario);
    c.consola.logout();
    c.consola.login(c.usuario);
    c.consola.changeUserPassword('clave','12456');
    c.usuario.password = '12456'
    c.consola.logout();
    c.consola.login(c.usuario);
    return assertTrue(c.consola.usuarioLogueado == c.usuario)
  });
```

**Comment by ngarbezza** [comment]
genial, recordá que podés hacer un `assertEquals(c.consola.usuarioLogueado, c.usuario)` en lugar del `assertTrue`

**Comment by tomasnozica** [comment]
perfecto ahi cambie por el equals!
