### ISSUE TITLE
Mejorar la forma en que se maneja si un usuario está logueado

### ISSUE THREAD

**Issue by ngarbezza** [tomasnozica/TerminalJavascript#5]
En lugar de tener dos variables `sesion` y `usuarioLogueado`, mucho mejor sería tener una sola (`usuarioLogueado`) que podría contener un null object para representar el caso donde ningún usuario está logueado.

https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/terminal.js#L7

**Comment by tomasnozica** [comment]
Lo reescribí de la siguiente manera:
```
login(usuario){
    if(this.validateUser(usuario)){
      this.usuarioLogueado = usuario;
    }
}
logout(){
    this.usuarioLogueado = null;
  }
validateUser(usuario){
    return this.usuarios.includes(usuario);
  }
```

**Comment by ngarbezza** [comment]
claro, pero seguís usando `null`... mejor sería tener ese objeto "no usuario" que te libera del `null` y te permite poder hacer acciones polimórficamente...

**Comment by tomasnozica** [comment]
oka, ahi cree el objeto nullUser del tipo Usuario. Se vera reflejado en la actualizacion
