### ISSUE TITLE
Generalizar Archivo y Directorio

### ISSUE THREAD

**Issue by ngarbezza** [tomasnozica/TerminalJavascript#7]
Se puede armar una jerarquía ya que ambos tienen un nombre. Además te va a servir para manejar el tema de permisos

https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/terminal.js#L46

**Comment by tomasnozica** [comment]
Profe antes de hacer los cambios, queria saber si es así como puedo manejar el tema de las jearquias
Por ejemplo:
```
var SystemElement = {
  init: function(name,owner){
    this.name = name;
    this.owner = owner;
    this.hijos = [];
  }
}
var Direc = Object.create(SystemElement);
Direc.ubicar = function(padre){
  this.padre = padre;
}
Direc.newElement = function(FileOrDirectory){
  this.hijos.push(FileOrDirectory);
}
Direc.deleteElement = function(FileOrDirectory){
  var index = this.hijos.indexOf(FileOrDirectory);
    if (index > -1) {
      this.hijos.splice(index, 1);
    }
}
Direc.back = function(FileorDirectory){
  return this.padre;
}
```
Otra duda que tengo, para que me funcione hijos tengo que declararlo en SystemElement pero no es correcto en la lógica porque archivos no va a tener hijos.
Lo pongo así en terminal.js? o es otra forma la que puedo establecer la jerarquia?

**Comment by tomasnozica** [comment]
Estuve pensando sobre esto profe y la verdad es que no se si me conviene porque es poco lo que tienen en común estas dos clases archivo y directorio.

**Comment by ngarbezza** [comment]
hmm, lo más fácil es usar la notación de clase que veníamos usando (que es muy parecido a como es en Java), y usar `super` cuando sea necesario:

```javascript
class Elemento {
   // codigo en común
}

class Archivo extends Elemento {
  // 
}

class Directorio extends Elemento {
  //
}
```

Si bien es cierto que tienen poco en común, conceptualmente sería lo correcto. Entonces, esta generalización sería más que para "compartir código", para organizar mejor el conocimiento y suma mucho que lo puedas implementar en tu TP

**Comment by tomasnozica** [comment]
Ahh ok ahi realice los cambios y quedo mucho mas limpio
