### ISSUE TITLE
Mover la creación del directorio dentro de la consola

### ISSUE THREAD

**Issue by ngarbezza** [tomasnozica/TerminalJavascript#9]
No está muy bueno que en el test tengamos que crear el directorio completo, ya que para eso hay que indicar cuál es su padre, y quién es su dueño. Estaría bueno que eso sea responsabilidad de la consola, algo así:

`consola.mkdir('directorio nuevo)` y que eso cree `directorio nuevo` donde sea que esté actualmente, con el usuario que esté logueado actualmente

https://github.com/tomasnozica/TerminalJavascript/blob/e477585aec5ed610679f1ae853b1f79ebab7ec8c/TPFinal/index.js#L118

**Comment by tomasnozica** [comment]
Ahora lo cambie y lo deje así:
```
mkdir(DirectorioName){
    return new Directorio(DirectorioName,this.directorioActual,this.usuarioLogueado);
  }
```

**Comment by ngarbezza** [comment]
perfecto!
